print('Welcome to the Band Name Generator.')
city_name = input("What's the name of the city you grew up in?\n")
city_name = city_name.capitalize()
pet_name = input("What's your pets  name?\n")
pet_name = pet_name.capitalize() 
print(f'Your band name could be {city_name} {pet_name}')